[workspace]
members = [".", "osiris-macros"]

[package]
name = "osiris"
version = "0.1.0"
edition = "2021"

[features]
unstable = ["io-uring/unstable"]
unsafe_completion = []
net = ["bstr"]
macros = ["osiris-macros"]


[profile.release]
debug = true

[dependencies]
bstr = { version = "1.5.0", optional = true, default-features = false, features = ["std"]}
libc = "0.2.138"
memchr = "2.5.0"
osiris-macros = { version = "0.1", path = "./osiris-macros", optional = true }
pin-project-lite = "0.2.9"
socket2 = "0.5.3"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.5.6" }


[dev-dependencies]
dotenv = "0.15.0"
osiris = { path = ".", features = ["unstable", "macros", "net"] }
