[package]
name = "osiris"
version = "0.1.0"
edition = "2021"

[features]


[profile.release]
debug = true

[dependencies]

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.5.6" }

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "*", features = ["full"] }
