[package]
name = "osiris"
version = "0.1.0"
edition = "2021"

[features]
unstable = ["io-uring/unstable"]

[profile.release]
debug = true

[dependencies]
io-uring = { version = "0.5.6" }
libc = "0.2.138"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { version = "0.5.6" }


[dev-dependencies]
dotenv = "0.15.0"
osiris = { path = ".", features = ["unstable"] }