version: "3.7"
services:
  linux:
    container_name: osiris
    build: .
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./:/root/osiris
      - /root/osiris/target
    command: "tail -f /dev/null"
    privileged: true
    tty: true
