version: "3.7"
services:
  linux:
    container_name: osiris
    build: .
    volumes:
      - ./:/root/osiris
      - /root/osiris/target
    command: "tail -f /dev/null"
    privileged: true
    tty: true
