# [build]
# target = "aarch64-unknown-linux-musl"


# [target.aarch64-unknown-linux-musl]
# runner = "docker run --rm -v /root/osiris/target -v .:/root/osiris -it rust:alpine"


# [target.wasm32-wasi]
# runner = "wasmer"
